name: Package
on:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v2

            - name: 'Install Volta'
              uses: volta-cli/action@v1

            - name: 'Install project'
              run: yarn install

            - name: 'Publish to npm'
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
